### ISSUE TITLE
Uncaught TypeError: Cannot read property 'kill' of null

### ISSUE THREAD

**Issue by rockofox** [morassman/process-palette#26] opened 2016-07-23 17:47 UTC
I spammed the stop button while multiple electron processes were open and my computer almost crashed

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [process-palette](https://github.com/morassman/process-palette) package, v0.8.3
### Stack Trace

Uncaught TypeError: Cannot read property 'kill' of null

```
At /Users/felixkranich/.atom/packages/process-palette/lib/controllers/process-controller.coffee:364

TypeError: Cannot read property 'kill' of null
  at ChildProcess.<anonymous> (/Users/felixkranich/.atom/packages/process-palette/lib/controllers/process-controller.coffee:364:22)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:818:16)
  at Socket.<anonymous> (internal/child_process.js:319:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:469:12)

```
### Commands

```
  7x -1:20.6.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:17.1.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:16.2.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
  2x -1:15.6.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
  4x -1:04.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:02.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -1:01.5.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:00.5.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -1:00.4.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:57.4.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  5x -0:56.2.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:47.2.0 Process Palette:Start (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:26.3.0 core:move-left (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:24.7.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:21.4.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:21.1.0 Process Palette:Start (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "atom-terminal",
      "atom-terminal-panel",
      "open-terminal-here",
      "autocomplete-java",
      "hyperclick",
      "tree-view",
      "omnisharp-atom",
      "activate-power-mode",
      "linter-gcc",
      "linter-jslint",
      "linter-jscs",
      "change-tabs",
      "linter-xmllint"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.meta",
      "*.o"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-terminal",
      "atom-terminal-panel",
      "open-terminal-here",
      "emmet",
      "sort-lines"
    ],
    "themes": [
      "excellent-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10
atom-easy-jsdoc, v4.6.0
atom-html-preview, v0.1.21
atom-ternjs, v0.14.2
atom-trello, v0.5.1
atom-yeoman, v0.3.15
autocomplete-clang, v0.9.4
autocomplete-computercraft, v1.0.0
autocomplete-emojis, v2.5.0
autocomplete-en-en, v0.2.0
autocomplete-folders, v0.4.1
autocomplete-glsl, v0.2.3
autocomplete-html-entities, v0.1.0
autocomplete-json, v5.1.0
autocomplete-love, v0.3.0
autocomplete-project-paths, v2.2.0
autocomplete-python, v1.8.2
autocomplete-ruby, v0.1.0
autocomplete-xml, v0.8.3
bottom-dock, v0.4.4
close-other-tabs, v0.1.0
color-picker, v2.2.2
documentation-renderer, v0.2.1
emmet, v2.4.3
excellent-ui, v2.2.1
file-types, v0.5.2
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
hyperclick, v0.0.37
hyperclick-love, v0.4.0
java-importer, v1.4.1
jsdoc-generator, v0.2.3
json-schema, v0.1.15
language-arduino, v0.4.1
language-babel, v2.32.0
language-common-lisp, v0.8.1
language-csharp, v0.12.1
language-glsl, v2.0.1
language-htaccess, v0.1.1
language-ini, v1.16.0
language-lisp, v0.2.0
language-lua, v0.9.4
language-ocaml, v1.1.2
language-ruby, v0.69.0
language-rust, v0.4.6
language-thrift, v1.0.2
language-unity-shaderlab, v1.0.1
language-x86, v1.0.1
linter, v1.11.14
linter-alex, v3.2.0
linter-clang, v3.4.4
linter-erb, v1.0.2
linter-javac, v1.9.4
linter-jshint, v2.1.0
linter-luaparse, v0.2.0
linter-manager, v0.2.12
linter-mcs, v0.2.0
linter-php, v1.2.0
linter-python, v3.0.4
linter-ruby, v1.2.2
linter-rust, v0.4.6
linter-tslint, v0.10.0
livereload, v0.4.4
love-ide, v0.12.0
maybs-quit, v1.3.0
merge-conflicts, v1.4.4
minimap, v4.24.7
nuclide, v0.157.0
pigments, v0.31.2
process-palette, v0.8.3
python-iresolve, v0.0.3
python-tools, v0.6.8
rails-i18n-autocomplete, v0.4.0
remote-sync, v4.1.2
save-autorun, v0.3.3
tab-switcher, v1.5.3
tab-title, v0.3.3
tidy-tabs, v0.3.0
todo-manager, v0.2.9
tool-bar, v1.0.0
tool-bar-main, v0.0.9
travis-ci-status, v1.1.1
vim-mode, v0.65.1
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by morassman** [comment] 2016-08-26 20:18
I think I found the cause of this bug. If I'm right then it should be fixed in the latest version (v0.9.0). I'm going to close this issue for now, so just log another bug if it happens again.

**Closed as completed by morassman** 2016-08-26 20:18 UTC
