### ISSUE TITLE
scroll lock re-enables itself

### ISSUE THREAD

**Issue by eschiebel** [morassman/process-palette#19] opened 2016-02-28 18:31 UTC
I run a command with stream: true. A few lines of output appear, then the scroll lock gets turned on without my touching anything. If I click the lock button to turn it off, the each time additional output appears in the panel, it turns itself back on again.

**Comment by rixo** [comment] 2017-11-24 15:01
Me too. Running tests in this, need to see the last results.

Commenting out this line fixes it: https://github.com/morassman/process-palette/blob/4762eb7adadeaa17c186910008ba8507eb74895f/lib/views/process-output-view.coffee#L80

This is some truly impressive job you've done here man. I somewhat regret not having more processes to run into Atom...

**Comment by morassman** [comment] 2017-11-24 16:46
The problem is definitely in that function. I've never been able to reproduce this issue though, so it's a bit tricky to debug.

Maybe if I test in, as far as possible, the same environment as you then I'll be able to reproduce it. Which OS are you using and what theme do you use in Atom?

**Comment by rixo** [comment] 2017-11-25 21:32
Ubuntu 16.04 / Atom Dark, but above all 4K display.

I've witnessed weird issues around scroll in Chrome with this screen and my own code.

I've done some debugging in your function: https://github.com/morassman/process-palette/blob/4762eb7adadeaa17c186910008ba8507eb74895f/lib/views/process-output-view.coffee#L88-L97

I've got the following values for example:

```js
this.outputPanel.height() + this.outputPanel.scrollTop()
// 168 + 232.81248474121094 => 400.81248474121094

this.outputPanel.get(0).scrollHeight 
// 390
```

Well, it's missing the height of the scrollbar apparently, but even with that:

```js
this.outputPanel.get(0).clientHeight + this.outputPanel.get(0).scrollTop 
// 158 + 232.81248474121094 => 390.81248474121094
```

Everything is rounded, except `scrollTop`, and so the equality test will always fail.

It does not happen inside jQuery as the last example shows. [According](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight) [to](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight) [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop), this is expected. IANAL but, to me, the spec doesn't seem to say that these should be rounded.

Anyway, I've done some quick testing with the following version of the test and that seems to fix the issue for me:

```coffee
    if ((@outputPanel.get(0).clientHeight + @outputPanel.scrollTop()) >= @outputPanel.get(0).scrollHeight)
```

As long as `clientHeight` and `scrollHeight` are rounded by the browser in the same way, that should work.

**Comment by adeemij** [comment] 2017-11-26 22:14
I have this issue as well.  I just wanted to add a comment: I have noticed that if you expand the dock window past the end of the (current) text, scroll lock only re-enables once the output reaches the end of the visible window.

**Comment by rixo** [comment] 2017-11-27 08:26
As a follow up, after some more usage, I keep having the issue with my proposed fix above. I don't have time to further investigate right now unfortunately.

**Comment by ghost** [comment] 2017-11-29 15:47
Confirming the issue as well, but for me it only happens if the window width is too small.

**Comment by morassman** [comment] 2018-02-03 20:06
I _might_ have fixed this with the latest patch. Since I haven't been able to reproduce this issue I cannot say for sure though. Please test with the latest version, v0.16.1, to see if you still experience this problem.

PS. @eschiebel You might not even be using process-palette anymore, but I'm soooo sorry for taking so long to get back to this issue!

**Comment by ghost** [comment] 2018-02-06 13:04
Fix works for me in 0.16.1.

**Comment by rixo** [comment] 2018-02-07 12:53
That seems to fix it for me too. Thanks!

**Comment by morassman** [comment] 2018-02-07 16:46
That's great news. I think it's safe to close the issue now.

Thanks for the feedback!

**Closed as completed by morassman** 2018-02-07 16:46 UTC
